"""Meester CLI.

    python -m meester harvest            # fetch, filter, dedupe, store
    python -m meester harvest --dry-run  # same, but write nothing
    python -m meester verify-companies   # probe every board token
    python -m meester show --limit 20    # print what is in the store
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import sys
from pathlib import Path

import yaml

from .harvest.run import harvest, verify_tokens
from .store import JobStore

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "config"


def _load(name: str) -> dict:
    path = CONFIG / name
    if not path.exists():
        sys.exit(f"missing config file: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _load_companies(explicit: str | None = None) -> dict:
    """Prefer the verified token list; fall back to the raw seed list.

    Roughly 40% of hand-written board tokens are wrong or stale, so harvesting
    straight from the seed file wastes a chunk of every run on 404s.
    """
    if explicit:
        return _load(explicit)
    if (CONFIG / "companies.verified.yaml").exists():
        return _load("companies.verified.yaml")
    print("note: no companies.verified.yaml - using unverified seed list.")
    print("      run `python -m meester verify-companies --write` first.\n")
    return _load("companies.yaml")


def _fmt(job) -> str:
    where = ",".join(job.remote_countries) or "?"
    age = job.age_days()
    age_s = f"{age:.0f}d" if age is not None else " ?"
    return f"  [{job.source[:4]:<4}] {age_s:>4}  {job.company[:18]:<18} {job.title[:56]:<56} ({where})"


async def cmd_harvest(args: argparse.Namespace) -> int:
    settings = _load("settings.yaml")
    companies = _load_companies(args.companies)

    jobs, report = await harvest(companies, settings)
    print(f"\n{report.summary()}\n")

    if report.boards_failed:
        print(f"failed boards ({len(report.boards_failed)}):")
        for ats, token, err in report.boards_failed[:15]:
            print(f"  {ats:<11} {token:<22} {err[:70]}")
        if len(report.boards_failed) > 15:
            print(f"  ... and {len(report.boards_failed) - 15} more")
        print("  (run `verify-companies` to prune dead tokens)\n")

    if args.dry_run:
        print(f"DRY RUN - nothing written. Top {min(args.limit, len(jobs))} of {len(jobs)}:\n")
        for job in jobs[: args.limit]:
            print(_fmt(job))
        return 0

    store_cfg = settings.get("store", {})
    store = JobStore(ROOT / store_cfg.get("path", "data/jobs.jsonl"),
                     ROOT / store_cfg.get("seen_path", "data/seen.json"))
    before = len(store)
    added = store.add_new(jobs)
    print(f"store: {before} known -> {len(store)} known ({len(added)} new)")

    # Regenerate the readable report every run. This is the only output anyone
    # other than a developer ever looks at, so it must never go stale - and a
    # failure here must not lose a successful harvest.
    try:
        from .report import build_report

        rows = [
            json.loads(line)
            for line in (ROOT / store_cfg.get("path", "data/jobs.jsonl"))
            .read_text(encoding="utf-8")
            .splitlines()
            if line
        ]
        out = build_report(rows, ROOT / store_cfg.get("report_path", "data/jobs.html"))
        print(f"report: {out}\n")
    except Exception as exc:  # noqa: BLE001
        print(f"warning: could not write report ({type(exc).__name__}: {exc})\n")

    for job in added[: args.limit]:
        print(_fmt(job))
    return 0


async def cmd_verify(args: argparse.Namespace) -> int:
    settings = _load("settings.yaml")
    companies = _load("companies.yaml")

    results = await verify_tokens(companies, settings)
    good: dict[str, list[str]] = {}
    for ats, tokens in results.items():
        ok = sorted(t for t, err in tokens.items() if not err)
        bad = sorted((t, err) for t, err in tokens.items() if err)
        good[ats] = ok
        print(f"\n{ats}: {len(ok)} live, {len(bad)} dead")
        for token, err in bad:
            print(f"  DEAD  {token:<22} {err[:60]}")

    total_ok = sum(len(v) for v in good.values())
    print(f"\n{total_ok} live board tokens total")

    if args.write:
        out = CONFIG / "companies.verified.yaml"
        header = (
            "# Auto-generated by `python -m meester verify-companies --write`.\n"
            "# Only tokens that actually resolved to a live board with postings.\n\n"
        )
        out.write_text(header + yaml.safe_dump(good, sort_keys=True), encoding="utf-8")
        print(f"wrote {out}")
    return 0


def cmd_report(args: argparse.Namespace) -> int:
    from .report import build_report

    settings = _load("settings.yaml")
    store_cfg = settings.get("store", {})
    path = ROOT / store_cfg.get("path", "data/jobs.jsonl")
    if not path.exists():
        print("store is empty - run `python -m meester harvest` first")
        return 1
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]
    out = build_report(rows, ROOT / store_cfg.get("report_path", "data/jobs.html"))
    print(f"report: {len(rows)} roles -> {out}")
    return 0


def cmd_show(args: argparse.Namespace) -> int:
    settings = _load("settings.yaml")
    path = ROOT / settings.get("store", {}).get("path", "data/jobs.jsonl")
    if not path.exists():
        print("store is empty - run `python -m meester harvest` first")
        return 0
    rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line]
    print(f"{len(rows)} jobs in store\n")
    for r in rows[-args.limit:]:
        where = ",".join(r.get("remote_countries") or []) or "?"
        print(f"  [{r['source'][:4]:<4}] {r['company'][:18]:<18} {r['title'][:56]:<56} ({where})")
    return 0


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.WARNING, format="%(levelname)s %(name)s: %(message)s")
    parser = argparse.ArgumentParser(prog="meester")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p_h = sub.add_parser("harvest", help="fetch, filter, dedupe and store")
    p_h.add_argument("--dry-run", action="store_true", help="write nothing")
    p_h.add_argument("--limit", type=int, default=25)
    p_h.add_argument("--companies", help="config filename to use (default: verified list)")

    p_v = sub.add_parser("verify-companies", help="probe every configured board token")
    p_v.add_argument("--write", action="store_true", help="write config/companies.verified.yaml")

    sub.add_parser("report", help="write the readable HTML report")

    p_s = sub.add_parser("show", help="print the local store")
    p_s.add_argument("--limit", type=int, default=25)

    args = parser.parse_args(argv)
    if args.cmd == "harvest":
        return asyncio.run(cmd_harvest(args))
    if args.cmd == "verify-companies":
        return asyncio.run(cmd_verify(args))
    if args.cmd == "report":
        return cmd_report(args)
    return cmd_show(args)


if __name__ == "__main__":
    raise SystemExit(main())
